### ISSUE TITLE
Error about the auto option

### ISSUE THREAD

**Issue by ofseed** [bennypowers/nvim-regexplainer#3]
It seems that when the initial position of the cursor is on the regular expression when the program starts, the auto option causes an error.

**Comment by bennypowers** [comment]
I tried to reproduce this by:
0. setting auto mode
1. deleting the first line of `tests/regexplainer/fixture.ts` (a comment)
2. quitting vim
3. `vim tests/regexplainer/fixture.ts`

I did not notice any errors.

Can you give me more information? How can I reproduce your issue?

**Comment by 1478zhcy** [comment]
![2022-03-08 22-33-47](https://user-images.githubusercontent.com/61115159/157260063-a9a51716-cd8b-4548-800d-829af9abd63b.gif)
I recorded a video to reproduce this situation. I use [neovim-session-manager](https://github.com/Shatur/neovim-session-manager) to restore the position of the last file edit. This should be pretty rare, but I just discovered it by accident, so it probably doesn't matter too much.

**Comment by 1478zhcy** [comment]
You can see that after reopening the file, every cursor movement will generate an error. But if you move the cursor out of the regex and back, everything works properly.

**Comment by bennypowers** [comment]
would you mind pasting the text of the error into this thread?

**Comment by bennypowers** [comment]
By the way, your GIF showed me another bug - multi-digit quantifiers were only showing the first digit (6-1x)

I fixed that in 2c782d1

**Comment by 1478zhcy** [comment]
Of course. 
```
Error executing vim.schedule lua callback: table index is nil
stack traceback:
        [C]: in function 'rawset'
        ...pack/packer/start/nui.nvim/lua/nui/utils/buf_storage.lua:13: in function '__index'
        ...ite/pack/packer/start/nui.nvim/lua/nui/utils/autocmd.lua:370: in function 'statement'
        ...ite/pack/packer/start/nui.nvim/lua/nui/utils/autocmd.lua:386: in function 'define'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:370: in function 'on'
        ...tart/nvim-regexplainer/lua/regexplainer/buffers/init.lua:108: in function 'render'
        ...pack/packer/start/nvim-regexplainer/lua/regexplainer.lua:75: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by 1478zhcy** [comment]
I tested again many times and I found that if I didn't immediately restore the last edited position (I quickly pressed a shortcut key in the video to restore), but stayed on the dashboard page for a second or two and then restored, then this The error no longer appears. and if I directly open the file and neovim restore the last edited position automatically, the error must occur, really weird.

**Comment by bennypowers** [comment]
I made some changes which are probably unrelated, but can you please update and try again, just in case?

**Comment by 1478zhcy** [comment]
Still the same situation as before. :(
I summarized several characteristics that trigger this error:

1. neovim automatically restores the cursor position of the last edit;
2. Manual restore after entering neovim, but at a very fast speed. The same manual recovery operation, if it is one-second slower, everything is normal;
3. The cursor stays on the regular expression when the position is restored;
4. When the cursor did not stay on the regular expression after the last edit, If you restore the cursor position automatically or very quickly manually, and then quickly move the cursor to the regular expression, there will be no errors;
5. After the error occurs, as long as the cursor remains on the regular expression, an error will be reported every time you move;
6. After the error occurs, move the cursor out of the regular expression and move it back, then there will be no error;

Considering the second point, I think it might also be a problem with neovim itself? Because the generation of errors depends on the startup speed. If it is difficult to reproduce on other devices, I think this error may also be the result of the interaction of my multiple plugins.

**Comment by ofseed** [comment]
Same problem as before, but the error message has changed
```
Error executing vim.schedule lua callback: ...gexplainer/lua/regexplainer/renderers/narrative/init.lua:39: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_call'
        ...gexplainer/lua/regexplainer/renderers/narrative/init.lua:39: in function 'set_lines'
        ...tart/nvim-regexplainer/lua/regexplainer/buffers/init.lua:200: in function 'render'
        ...pack/packer/start/nvim-regexplainer/lua/regexplainer.lua:109: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
It's really a small issue and is affected by uncertain factors like the speed at which files are opened, perhaps due to plugins interacting with each other. Since this issue has been open for a while, no one has reported the same situation, and it is difficult to reproduce on other machines, maybe we can close it now?

**Comment by bennypowers** [comment]
If you have an idea for a testable pr I'm so for it. Thanks for the report
