### ISSUE TITLE
Support for unicode escape characters

### ISSUE THREAD

**Issue by ekorchmar** [bennypowers/nvim-regexplainer#44]
Currently, regex like `/[\u005D-\uFFFF]/`: is parsed as a set of literals, not as a unicode range:
```
One of `u`, `0`, `0`, `5`, `D-\\u`, `F`, `F`, `F`, or `F`
```

It should be something like:
```
One of \u005D-\uFFF
```

**Comment by bennypowers** [comment]
![image](https://github.com/bennypowers/nvim-regexplainer/assets/1466420/5fb30d2c-ee9e-4978-a072-41ecd775ba74)
It looks to me like this [needs to be fixed in the treesitter parser](https://github.com/tree-sitter/tree-sitter-regex/blob/47007f195752d8e57bda80b0b6cdb2d173a9f7d7/grammar.js#L149-L152)

we could in theory implement a workaround here by examining the quality of the escape sequence and parsing it ourselves but I sleep...

**Comment by bennypowers** [comment]
I'm closing this for now as WONTFIX because I believe it's best addressed in the parser. Any who wish to prove me wrong, or provide (and maintain!) a PR to work around this issue in lua, are welcome to comment here and I'll reopen.

**Comment by bennypowers** [comment]
Please see https://github.com/tree-sitter/tree-sitter-regex/pull/28 as there are some caveats to be aware of

**Comment by ekorchmar** [comment]
Yes -- I wrote about them :smile:
